### ISSUE TITLE
Supporting read only SignedJar?

### ISSUE THREAD

**Issue by KeenS** [SergioBenitez/cookie-rs#101]
Current [signed](http://alexcrichton.com/cookie-rs/cookie/struct.CookieJar.html#method.signed) method requires `&mut self` even if you need only reading the value. And I guess PrivateJar has the same problem.
Are there any chance to support read only SignedJar that can be obtained from non-mutable `self` and serves only `get` method?

**Comment by SergioBenitez** [comment]
The `sync` branch is resolving this issue.
