### ISSUE TITLE
How can I unset a path?

### ISSUE THREAD

**Issue by tversteeg** [SergioBenitez/cookie-rs#108]
It appears it's possible to set the path but is it possible to unset it once it's set? Passing `""` doesn't help..

**Comment by SergioBenitez** [comment]
This is #91, which hasn't been merged because 1) the API isn't as nice as I'd like it to be, and 2) there isn't enough motivation for it. What's your motivation?

**Comment by tversteeg** [comment]
My motivation was to put a received HTTP header Set-Cookie into a `Cookie::parse`, remove the path, convert it to a string and send it back as a HTTP header Cookie (without the path).

**Comment by SergioBenitez** [comment]
In 0.13: `Cookie::set_path(None)`.
