### ISSUE TITLE
Options for `secure` feature with a different crypto library?

### ISSUE THREAD

**Issue by anp** [SergioBenitez/cookie-rs#113]
Hello! What do you think about adding some indirection over the ring APIs used in this crate and optionally allowing users to choose openssl/boring/mundane/etc for their crypto implementation? It would obviously have (potentially severe?) security and ergonomics tradeoffs to consider, but having a more stable option would be very nice given the recent mass-yanking of ring versions.

**Comment by SergioBenitez** [comment]
`cookie` now uses `RustCrypto` for pure-Rust based cryptography, ideally resolving this issue.
