### ISSUE TITLE
Release with updated ring dependency

### ISSUE THREAD

**Issue by djmitche** [SergioBenitez/cookie-rs#115]
This is a follow-on from https://github.com/taskcluster/rust-hawk/pull/14, where @eoger mentions that old versions of ring are regularly yanked.  In particular, this is preventing me from using the latest rust-hawk with rocket:

```
error: failed to select a version for `ring`.
    ... required by package `hawk v1.0.5`
    ... which is depended on by `rocket-play v0.1.0 (/home/dustin/tmp/rocket-play)`
versions that meet the requirements `^0.14.5` are: 0.14.6, 0.14.5

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.13.5`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `rocket_http v0.4.0`
    ... which is depended on by `rocket v0.4.0`
    ... which is depended on by `rocket-play v0.1.0 (/home/dustin/tmp/rocket-play)`
```

I see that ring is already upgraded in master, but not released.  Would you consider making a release?

**Comment by Brooooooklyn** [comment]
I need this too.
Temporary workaround:
```toml
[replace]
"cookie:0.11.0" = { git = 'https://github.com/alexcrichton/cookie-rs.git' }
```

**Comment by colelawrence** [comment]
I'm experiencing the same issue between `rustls ^0.15` used by one dependency (depends on `ring ^0.14`) and `actix-web ^0.7` which depends on `cookie ^0.11` (`ring ^0.13`)
```
error: failed to select a version for `ring`.
    ... required by package `rustls v0.15.0`
    ... which is depended on by `http_req v0.4.6 (/Users/colelawrence/Desktop/playbar/password/http_req)`
    ... which is depended on by `password v0.1.0 (/Users/colelawrence/Desktop/playbar/password)`
    ... which is depended on by `playbar v0.1.0 (/Users/colelawrence/Desktop/playbar)`
versions that meet the requirements `^0.14` are: 0.14.6, 0.14.5, 0.14.4, 0.14.3, 0.14.2, 0.14.1, 0.14.0

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.13.5`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `actix-web v0.7.18`
    ... which is depended on by `sj_ui v0.1.0 (/Users/colelawrence/Desktop/playbar/sj_ui)`
    ... which is depended on by `playbar v0.1.0 (/Users/colelawrence/Desktop/playbar)`

failed to select a version for `ring` which could resolve this conflict
```

**Comment by colelawrence** [comment]
> I need this too.
> Temporary workaround:
> 
> ```toml
> [replace]
> "cookie:0.11.0" = { git = 'https://github.com/alexcrichton/cookie-rs.git' }
> ```

I was able to make it work using the suggested replace!
I had to place the replace at my workspace root file, then I also added a specific revision.

```toml
[replace]
"cookie:0.11.0" = { git = 'https://github.com/alexcrichton/cookie-rs.git', rev = "c59d94e1492f2aa8ce0949335d494322ca25366e" }
```

**Comment by apiraino** [comment]
I need this, too :-) it also breaks latest [jsonwebtoken](https://crates.io/crates/jsonwebtoken) (v6.0)

thanks

**Comment by SergioBenitez** [comment]
On it.

**Comment by SergioBenitez** [comment]
0.12 has been released!

**Comment by RohithCIS** [comment]
We need another update-deps. Breaks jsonwebtoken 7.1.0.
```failed to select a version for `ring`.
    ... required by package `jsonwebtoken v7.1.0`
versions that meet the requirements `^0.16.5` are: 0.16.13, 0.16.12, 0.16.11, 0.16.10, 0.16.9, 0.16.7, 0.16.6, 0.16.5

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.13.5`
    ... which is depended on by `cookie v0.11.2`
    ... which is depended on by `rocket_http v0.4.4`
    ... which is depended on by `rocket v0.4.4`
    ... which is depended on by `rocket_contrib v0.4.4`
failed to select a version for `ring` which could resolve this conflict```

**Comment by SergioBenitez** [comment]
`cookie` is moving away from `ring` in `0.14`, so this should be a mute issue soon, @RohithCIS.
