### ISSUE TITLE
Add support for cookies that are not utf-8

### ISSUE THREAD

**Issue by ghost** [SergioBenitez/cookie-rs#116]
~~Maybe add `Cookie::parse_bytes` to avoid breaking changes.~~

It would allow actix-web to detect some cases when the key for private cookies is leaked (https://github.com/actix/actix-web/issues/734)

Edit: after all it seems impossible to add this feature without breaking changes...

**Comment by SergioBenitez** [comment]
Looks like this was resolved downstream.

**Comment by bnoordhuis** [comment]
Can I request this be revisited? I ran into this as well.

**Comment by SergioBenitez** [comment]
@bnoordhuis According to [RFC #6265](https://tools.ietf.org/html/rfc6265) and 2616, non-ASCII characters are not allowed in cookie values:

```
 cookie-name       = token
 cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
 cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                       ; US-ASCII characters excluding CTLs,
                       ; whitespace DQUOTE, comma, semicolon,
                       ; and backslash
 token             = 1*<any CHAR except CTLs or separators>
 CHAR              = <any US-ASCII character (octets 0 - 127)>
```

Chrome and Opera seem to allow UTF-8, and Firefox seems to sort-of allow UTF-8, but I cannot find any indication of any browser supporting non-UTF-8, and certainly not arbitrary bytes. What is your use-case?

**Comment by bnoordhuis** [comment]
I observed that in the wild some clients and servers send latin-1. I'm aware of the spec but rejecting non-compliant HTTP requests and responses wasn't an option for me. I solved it by writing a custom cookie parser.
