### ISSUE TITLE
Release version with ring 0.14

### ISSUE THREAD

**Issue by DoumanAsh** [SergioBenitez/cookie-rs#117]
Since ring `0.13.` will be yanked soon, we need a new version of `cookie` asap so that we would have version with bumped `cookie` dep

CC owners @SergioBenitez @alexcrichton

**Comment by DoumanAsh** [comment]
For these who would need temporarily solution, I published forked `cookie` for now https://crates.io/crates/cookie2

API is the same, just updated to 2018 edition

**Comment by repi** [comment]
Ran into this issue as well, would be great to have a new published cookie 0.12 crate that uses ring 0.14 instead of 0.13, as one can only have a single version of `ring` linked in.

**Comment by SergioBenitez** [comment]
See #110.
