### ISSUE TITLE
Please separate "secure" feature into a different crate

### ISSUE THREAD

**Issue by seanmonstar** [SergioBenitez/cookie-rs#120]
I realize its an optional feature, but even libraries that don't care care about signing cookies are still disrupted when breaking changes of *ring* are released (for example, https://github.com/seanmonstar/reqwest/issues/517). If they were separate crates, the core `Cookie` API could be more stable, and then only `cookie-secure` (naming is hard) would ever need to update for new *ring* versions.

**Comment by ignatenkobrain** [comment]
For the Fedora, we would appreciate if we could get an option to use openssl or native-tls or whatsoever because we are not willing to package another crypto-library (ring). I don't have anything against code or person, but we just try to avoid yet another crypto libraries.

**Comment by newpavlov** [comment]
Considering that this crate no longer depends on ring, is it still an issue? (IIRC Fedora already packages some RustCrypto crates)

**Comment by SergioBenitez** [comment]
I'm going to assume this is no longer issue since we no longer depend on `ring`; please correct me if I'm wrong!
