### ISSUE TITLE
Static lifetime to build a new cookie

### ISSUE THREAD

**Issue by yaa110** [SergioBenitez/cookie-rs#123]
Why the lifetime of parameters to create  a new cookie `Cookie::build(name, value)` is `static`?

**Comment by SergioBenitez** [comment]
For simplicity, and to make the common case simply. You can presently use `parse()` if you need a different lifetime. I would consider a PR that changes the defaults, however.

**Comment by SergioBenitez** [comment]
This has been changed in master.
