### ISSUE TITLE
Minimum supported Rust version?

### ISSUE THREAD

**Issue by jhpratt** [SergioBenitez/cookie-rs#130]
What is the current MSRV for Cookie, and the threshold for upping it? As the revamped time crate is nearing release, it looks doable to update the dependency here. However, the MSRV for that is 1.40.

Both of these would changes would necessarily bump the MSRV (and necessitate a 0.13 release), though `#[non_exhaustive]` would be useful elsewhere as well.

Basically, I'd like to make changes similar to those I made for Rocket (which were well-received!). I'm just curious if bumping the MSRV is allowed, and by how much.

**Comment by jhpratt** [comment]
Ping @SergioBenitez. v0.2 will be released tomorrow.

**Comment by jhpratt** [comment]
Ping @SergioBenitez. I have updated cookie to 2018 edition and to time v0.2 on a local branch. Would a PR be accepted? Cookie is one of the largest crates that has a runtime dependency on time, and this upgrade would also have slight memory improvements. This upgrade would also allow other crates, such as reqwest, to upgrade.

**Comment by SergioBenitez** [comment]
Current MSRV is likely 1.34 due to use of `TryFrom` in `base64`. Ideally we can keep 1.34 as the MSRV. I have no issues with updating to 2018 or time v0.2; the PR would indeed be accepted.
