### ISSUE TITLE
ring dependency version 

### ISSUE THREAD

**Issue by CedricCouton** [SergioBenitez/cookie-rs#131]
Hi,

When the next release of 0.12 is targeted in order to take in consideration the 0.16 version of ring?

Thanks

**Comment by djc** [comment]
Hi @SergioBenitez, would you like some help maintaining this crate? It's a bit sad that this crate is running two versions behind released *ring* at this point. I'm happy to help out or take over if you like.

**Comment by SergioBenitez** [comment]
We need a major version bump to update ring. My last consideration is updating the `time` crate as well, immediately after which I'll push 0.13.

**Comment by djc** [comment]
I started this in #134. I think the time crate needs some improvements first, though, see https://github.com/time-rs/time/issues/202.

**Comment by SergioBenitez** [comment]
0.13 has been released with an up-to-date `ring`.

**Comment by djc** [comment]
Thanks!
