### ISSUE TITLE
now_utc() not found

### ISSUE THREAD

**Issue by MartinKavik** [SergioBenitez/cookie-rs#148]
Hey guys, I think I've found a bug - `OffsetDateTime::now_utc()` not found.

<details>
<summary>Error details</summary>

```bash
error[E0599]: no function or associated item named `now_utc` found for struct `time::OffsetDateTime` in the current scope
   --> C:\Users\Martin\.cargo\registry\src\github.com-1ecc6299db9ec823\cookie-0.14.0\src\lib.rs:854:42
    |
854 |         self.set_expires(OffsetDateTime::now_utc() + twenty_years);
    |                                          ^^^^^^^ function or associated item not found in `time::OffsetDateTime`

error[E0599]: no function or associated item named `now_utc` found for struct `time::OffsetDateTime` in the current scope
   --> C:\Users\Martin\.cargo\registry\src\github.com-1ecc6299db9ec823\cookie-0.14.0\src\jar.rs:229:48
    |
229 |             cookie.set_expires(OffsetDateTime::now_utc() - Duration::days(365));
    |                                                ^^^^^^^ function or associated item not found in `time::OffsetDateTime`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `cookie`.
```
</details>

I think the problem is old `time` dependency:
https://github.com/SergioBenitez/cookie-rs/blob/9b165d6fda6f707c9799c5d1794f782691ce6e4c/Cargo.toml#L22
Version `0.2.6` doesn't have method `OffsetDateTime::now_utc` - see [docs.rs](https://docs.rs/time/0.2.6/time/struct.OffsetDateTime.html#method.now). The method is available in `time` >= [0.2.11](https://docs.rs/time/0.2.11/time/struct.OffsetDateTime.html#method.now_utc)

- `cookie` v. `0.13.3` works great, the problem is only in `0.14.0`.
- I've found the issue while I was upgrading dependencies in [Seed](https://github.com/seed-rs/seed). Tested on Windows; `target` folder and deps cache deleted.

Thank you!

**Comment by SergioBenitez** [comment]
A `cargo update` should get you a version of `time` with the method as `0.2.6` implies `>= 0.2.6, < 0.3.0`. Nevertheless, we should explicitly request a version of `time` with the methods to avoid any issues like this. Thanks for reporting.

**Comment by SergioBenitez** [comment]
`0.14.1` is out with the proper `time` version string.
