### ISSUE TITLE
Avoid polluting signed cookies

### ISSUE THREAD

**Issue by Fishrock123** [SergioBenitez/cookie-rs#159]
It would be nice if instead of polluting signed cookies, there was an easy way to have the raw cookie sit alongside a signature cookie. This would greatly help any intermediaries, i.e. a proxy or other routing be able to use cookies in some way, where it may not need to re-verify those. 

This is inspired by [Express.js's cookies middleware](https://github.com/pillarjs/cookies) which keeps the raw cookie and then also makes an additional cookie with the signature and `name + ".sig"`.

**Comment by SergioBenitez** [comment]
I think an additional child jar, or perhaps a setting on the existing `Signed` jar, that enables this functionality would be great.

**Comment by SergioBenitez** [comment]
This has been sitting here for years. I'm not opposed to the idea, and I would review such an implementation. But given no other requests, I'm closing this out.
