### ISSUE TITLE
Parser incorrectly parses years in some cases

### ISSUE THREAD

**Issue by except** [SergioBenitez/cookie-rs#162]
Consider the following Set-Cookie header - 
`foo=bar; expires=Thu, 10-Sep-20 20:00:00 GMT;`

This should be parsed as `2020-09-10 20:00 +0` however expires returns `0020-09-10 20:00 +0`

**Comment by jhpratt** [comment]
After a quick discussion, this behavior is correct as intended on time's end — the century will not be assumed.

Apparently this originates from Cloudflare, which isn't actually following the spec (emphasis mine)

>  HTTP/1.1 clients and servers that parse the date value MUST accept
   all three formats (for compatibility with HTTP/1.0), **though they MUST
   only generate the RFC 1123 format for representing HTTP-date values
   in header fields.**

The first part of that doesn't actually specify what _should_ happen when encountering a two-digit year, though I can't find anything along those lines in any RFC. As such, I think it's best to follow browsers' behavior. Apparently Chrome uses the following code (@except can you provide a source?)

```c
// Normalize the year to expand abbreviated years to the full year.
if (exploded.year >= 69 && exploded.year <= 99)
  exploded.year += 1900;
if (exploded.year >= 0 && exploded.year <= 68)
  exploded.year += 2000;
```

This essentially assumes the year is between 1969 and 2068 inclusive.

Unfortunately, the only way to adjust the year is to fully reconstruct a `PrimitiveDateTime` from its components. Having a better API for operations along these lines is tracked in time-rs/time#256.

**Comment by except** [comment]
Source to where [Chromium](https://chromium.googlesource.com/chromium/src/net/+/master/cookies/cookie_util.cc#316) corrects two-digit based years.

**Comment by jhpratt** [comment]
For the record: I have just submitted a request to Cloudflare. Regardless, this crate's behavior is also not spec compliant.

**Comment by except** [comment]
Firefox uses PR_ParseTimeString ([PR_ParseTimeStringToExplodedTime](https://hg.mozilla.org/mozilla-central/file/tip/nsprpub/pr/src/misc/prtime.c#l1469)) which does something similar when [parsing](https://hg.mozilla.org/mozilla-central/file/tip/netwerk/cookie/CookieService.cpp#l1908).

```c++
year = n1;
if (year < 70) {
    year += 2000;
}
else if (year < 100) {
    year += 1900;
}
```

WebKit using parseExpiresMS ([WTF::parseDateFromNullTerminatedCharacter](https://github.com/WebKit/webkit/blob/master/Source/WTF/wtf/DateMath.cpp#L964)) also [parses](https://github.com/WebKit/webkit/blob/master/Source/WebCore/platform/network/curl/CookieUtil.cpp#L131) slightly differently. 

```c++
if (year) {
    int yearValue = year.value();
    if (yearValue >= 0 && yearValue < 100) {
        if (yearValue < 50)
            yearValue += 2000;
        else
            yearValue += 1900;
    }
    year = yearValue;
}
```

**Comment by SergioBenitez** [comment]
Thank you for the input, all!
