### ISSUE TITLE
0.14.3 w/ new aes-gcm version

### ISSUE THREAD

**Issue by Licenser** [SergioBenitez/cookie-rs#167]
Hi,
is there a chance we get a 0.14.3 releas with the updated aes-gcm update? Currently, the 0.8 dependency throws warnings for `block-cipher` having been renamed: https://github.com/tremor-rs/tremor-runtime/issues/539

Many thank in advance :) and thank you for all the hard work! <3

**Comment by SergioBenitez** [comment]
`0.14.3` has been released with updated RustCrypto deps!

**Comment by Licenser** [comment]
Thank you! <3
