### ISSUE TITLE
Parser ignores all except last domain= key

### ISSUE THREAD

**Issue by bnoordhuis** [SergioBenitez/cookie-rs#168]
cookie@0.14.3

```rust
Cookie::parse("q=42; domain=evil.com; domain=good.org").unwrap().domain() // Some("good.org")
```
I feel the overly permissive behavior here introduces security vulnerabilities in downstream users that use `cookie` to validate cookies.

Real world example: I want my http proxy to reject cookies from upstream (who I don't necessarily trust) if they don't match the upstream domain but that's currently all too easy to circumvent.

(Possibly applies to `path=` too, I didn't check.)

**Comment by pfernie** [comment]
The behavior of taking the last specified domain value is a described in the [RFC 6265 spec](https://tools.ietf.org/html/rfc6265#page-20)

```
  4.   If the cookie-attribute-list contains an attribute with an
        attribute-name of "Domain":

           Let the domain-attribute be the attribute-value of the last
           attribute in the cookie-attribute-list with an attribute-name
           of "Domain".

        Otherwise:

           Let the domain-attribute be the empty string.
```

**Comment by bnoordhuis** [comment]
Fair enough, but there are plenty of cookie parsers that don't follow that aspect of the spec. Random example:

https://github.com/jshttp/cookie/blob/243fa7edab7f213a6af8adb339e9530daa23b445/index.js#L76-L79

That's a pretty popular package, 22 million downloads/week.

(I'll open an issue with them but I don't know if they're willing to fix that.)

If you think `cookie` is in the clear here, then please go ahead and close the issue.

**Comment by SergioBenitez** [comment]
We'll follow the spec on this one.
