### ISSUE TITLE
Parse multiple cookies in single string?

### ISSUE THREAD

**Issue by muscache** [SergioBenitez/cookie-rs#192]
HTTP clients must send a single `Cookie:` header with all the cookies separated by a `; ` according to [RFC 6265](https://www.rfc-editor.org/rfc/rfc6265#section-5.4).

If I attempt to parse such a header, I only get the first cookie:

```rust
let cookie_str = "__Secure-A=AAA; __Secure-B=BBB";

// Only returns first cookie, '__Secure-A'.
cookie::Cookie::parse(cookie_str).unwrap();
```

Currently I manually split the header value by ';' and parse each cookie. It would be nice to have a method eg. `parse_multiple` that returns a `Vec<Cookie>`

**Comment by SergioBenitez** [comment]
See #156 and #137.
