### ISSUE TITLE
0.16 release

### ISSUE THREAD

**Issue by LukeMathWalker** [SergioBenitez/cookie-rs#193]
`cookies` has had a 0.16.0 release candidate out for a few months now - is there a timeline for a non-rc release?

Looking primarily to upgrade to `time` `0.3`, which looks like the key breaking change in `0.16`.

**Comment by alexcrichton** [comment]
Sorry but I no longer mantain this crate, so I don't think I can help here.

**Comment by SergioBenitez** [comment]
Released.
