### ISSUE TITLE
Iterator over all cookies from string

### ISSUE THREAD

**Issue by Chaostheorie** [SergioBenitez/cookie-rs#198]
I would like to add `parse` convenience method to `CookieJar` that allows a developer to parse a string with multiple cookies. It would most likely be a rather simple method, like the following pseudocode:

```rust 
pub fn parse<'c, S>(s: S) -> Result<CookieJar, ParseError>
where
    S: Into<Cow<'c, str>>,
{
    s.split(';').try_fold(CookieJar::new(), |mut jar, cow| {
        jar.add_original(Cookie::parse(cow)?);
        Ok(jar)
    })
}
```

If such a method fit into the design of cookie, I'd like to contribute it. 

Background: A developer has requested an iterator over all cookies present in a string as part of a discussion in the [Actix Web project](https://github.com/actix/actix-web/issues/2575).

**Comment by frederikhors** [comment]
@SergioBenitez this would be very awesome! I'm too newbie to contribute with a PR! 😄
