### ISSUE TITLE
aes-gcm vulnerability

### ISSUE THREAD

**Issue by forest1102** [SergioBenitez/cookie-rs#219]
For security issue, it is recommended to upgrade `aes-gcm` version to v10.0.3.   
https://security.snyk.io/vuln/SNYK-RUST-AESGCM-5916453

**Comment by SergioBenitez** [comment]
There's nothing to do here. Simply `cargo update`. We don't control which version is used - that's up to the library depending on `cookie`. We only specify the minimum version.
