### ISSUE TITLE
Does cookie-rs support cookie "Partitioned" yet, please?

### ISSUE THREAD

**Issue by behai-nguyen** [SergioBenitez/cookie-rs#224]
Hi,

I have raised this question with the ``actix-web`` repo: [Does actix-web support cookie "Partitioned" yet, please?](https://github.com/actix/actix-web/discussions/3284).

I am advised to raise with you. **Please find below the full text of the question.**

Hi,

My ``actix-web`` server uses cross-site cookies.

Latest Edge reports the following warnings:

```
Reading cookie in cross-site context will be blocked in future Chrome versions

Cookies with the SameSite=None; Secure and not Partitioned attributes that operate in cross-site contexts are third-party cookies. In future Chrome versions, reading third-party cookies will be blocked. This behavior protects user data from cross-site tracking.
```

This Mdm Web Docs [Cookies Having Independent Partitioned State (CHIPS)](https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies) explains cookie ``Partitioned``.

With ``actix-web`` 4.5.1, I have looked through [Struct actix_web::cookie::Cookie](https://docs.rs/actix-web/latest/actix_web/cookie/struct.Cookie.html), and there seems to be no method to set ``Partitioned`` yet?

I am correct to think that ``actix-web`` 4.5.1 support cookie "Partitioned" yet, or please?

Thank you and best regards,

...behai.

**Comment by SergioBenitez** [comment]
It does, it just hasn't even release yet. In the future, please see existing closed issues before opening a new one.
