### ISSUE TITLE
Use Z85 encoding HMAC values and encrypted values

### ISSUE THREAD

**Issue by briansmith** [SergioBenitez/cookie-rs#78]
[Z85](https://rfc.zeromq.org/spec:32/Z85/) is like Base64, but instead of encoding 3 bytes in 4 ASCII characters, it encodes 4 bytes in 5 ASCII characters. The constraints placed on the design of Z85 also happen to make every Z85 encoding character a valid cookie value character. (Valid values in a cookie value are documented as `cookie-octet` in [RFC 6265 Section 4.1.1](https://tools.ietf.org/html/rfc6265#section-4.1.1).

In the case of HMAC-SHA256-signed , this would reduce 12 bytes of base64-encoding overhead to 8 bytes of Z85 encoding overhead, which isn't really significant. For *encrypted-and-signed* cookies the savings could be more significant.

This would remove the rustc-serialize dependency, which also seems desirable. (This could also be done by switching to the base64 crate or an alternative.)

**Comment by briansmith** [comment]
There are at least two Z85 crates already existing: https://crates.io/crates/z85 and https://crates.io/crates/zero85.

**Comment by alexcrichton** [comment]
This sounds like a great idea!

@SergioBenitez this'd provide an awesome alternative to rustc-serialize in your CookieJar rewrite (https://github.com/alexcrichton/cookie-rs/pull/76)

**Comment by SergioBenitez** [comment]
I like this idea, but I'm worried about the two crates you linked. Actually, they both point to the same repository, so I suppose there's only one. The crate has no documentation, and testing seems sparse (I don't understand [this quickcheck discard, for instance](https://github.com/emreyaren/zero85/blob/master/tests/lib.rs#L30-L32)). It hasn't been touched in over a year, and it's not used by any published crates. We could take the time to vet and improve the crate, or create another one, I suppose.

**Comment by briansmith** [comment]
Any problems like that seem solvable.

@emreyaren Are you still maintaining your Z85 crate?

**Comment by reddraggone9** [comment]
It's probably worth noting there's only 219 lines of rust in [emreyaren/zero85](https://github.com/emreyaren/zero85) (including blank lines), zero build dependencies, and it's licensed the same as this crate.

**Comment by SergioBenitez** [comment]
Let's stick with `base64` until there's a compelling crate.

**Comment by decafbad** [comment]
I added padding to Z85 now. Tell me if anything is wrong with 3.0.2 version.
https://github.com/decafbad/z85
