### ISSUE TITLE
How to iterate over cookies of SignedJar?

### ISSUE THREAD

**Issue by XX** [SergioBenitez/cookie-rs#95]
The SignedJar doesn't have iteration methods. How to iterate over cookies in this case?

**Comment by ivstas** [comment]
@XX you probably have retrieved `SignedJar` from `CookieJar`, which become a parent for retrieved jar. Changes to retrieved jar are actually done on parent jar, so you can iterate over parent's `delta` to get the cookies of `SignedJar`

**Comment by SergioBenitez** [comment]
In master, you can now do:

```rust
// assuming `parent` is the parent cookie jar:
for cookie in parent.iter().filter_map(|c| SignedJar::verify(c.clone()).ok()) { .. }
```
