### ISSUE TITLE
Raw (bytes) percent encoded values

### ISSUE THREAD

**Issue by ishitatsuyuki** [SergioBenitez/cookie-rs#98]
Some frameworks puts control characters into cookies. In my case, [Revel](https://github.com/revel/revel/blob/master/flash.go) puts NUL in cookies percent encoded.

The current API doesn't allow straight handling of this (I need to go through `percent_encoding` directly).

**Comment by SergioBenitez** [comment]
The `percent-encoding` feature has handled this for some time now.
